=== pietro-nardelli/Stoudy/xml-schema/admins.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple element -->
	<xsd:element name="email" type="xsd:string" />
	<xsd:element name="riassuntoID" type="xsd:string" />

	<!-- definition of attributes -->
	<!-- definition of complex elements -->
	<xsd:element name="admin">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="email" />
				<xsd:element ref="riassuntoID" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="admins">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="admin"  minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pietro-nardelli/Stoudy/xml-schema/admins.xml
<?xml version="1.0" enIDing="UTF-8"?>
<admins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="admins.xsd">
	<admin>
		<email>admin1@gmail.com</email>
		<riassuntoID>123411</riassuntoID>
	</admin>
	<admin>
		<email>admin2@gmail.com</email>
		<riassuntoID>123412</riassuntoID>
		<riassuntoID>123491</riassuntoID>
	</admin>
	<admin>
		<email>admin3@gmail.com</email>
	</admin>
</admins>
