=== pietro-nardelli/Stoudy/xml-schema/revisioni.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple element -->
	<xsd:element name="nomeTag" type="xsd:string" />
    <xsd:element name="modificaEstratto" type="xsd:string" />
	<xsd:element name="emailAdmin" type="xsd:string" />
	<xsd:element name="emailStudente" type="xsd:string" />


	<!-- definition of attributes -->
	<!-- definition of complex elements -->
	<xsd:element name="revisione">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nomeTag" />
				<xsd:element ref="emailAdmin" />
                <xsd:element ref="modificaEstratto" />
                <xsd:element ref="emailStudente" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="revisioni">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="revisione"  minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pietro-nardelli/Stoudy/xml-schema/revisioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<revisioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="revisioni.xsd"><revisione><nomeTag>CiAo</nomeTag><emailAdmin>admin1@gmail.com</emailAdmin><modificaEstratto>Questo estratto è riferito al tag ciao che significa blabla e che non avevo voglia di scrivere altro perchè poi mi rompevo le palle.</modificaEstratto><emailStudente>pietro.nardelliz@gmail.com</emailStudente></revisione><revisione><nomeTag>cazzo</nomeTag><emailAdmin>admin1@gmail.com</emailAdmin><modificaEstratto>oiolaiolaila</modificaEstratto><emailStudente>pietro.nardelliz@gmail.com</emailStudente></revisione><revisione><nomeTag>ciao2</nomeTag><emailAdmin>admin2@gmail.com</emailAdmin><modificaEstratto>bl</modificaEstratto><emailStudente>pietro.nardelliz@gmail.com</emailStudente></revisione></revisioni>
