=== pietro-nardelli/Stoudy/xml-schema/riassunti.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple element -->
	<xsd:element name="ID" type="xsd:nonNegativeInteger" />
	<xsd:element name="titolo" type="xsd:string" />
	<xsd:element name="emailStudente" type="xsd:string" />
	<xsd:element name="data" type="xsd:date" />
	<xsd:element name="orario" type="xsd:time" />
	<xsd:element name="descrizione" type="xsd:string" />
	<xsd:element name="linkDocumento" type="xsd:string" />
	<xsd:element name="emailPreferiti" type="xsd:string" />
	<xsd:element name="visualizzazioni" type="xsd:nonNegativeInteger" />
	<xsd:element name="nomeTag" type="xsd:string" />

	<!-- definition of attributes -->
	<xsd:attribute name="condivisione">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="privato" />
				<xsd:enumeration value="pubblico" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>

	<xsd:attribute name="lastID">
		<xsd:simpleType>
			<xsd:restriction base="xsd:nonNegativeInteger" />
		</xsd:simpleType>
	</xsd:attribute>


	<!-- definition of complex elements -->
	<xsd:element name="tags">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nomeTag" minOccurs="1" maxOccurs="5" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="preferiti">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="emailPreferiti"  minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="riassunto">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="ID" />
				<xsd:element ref="titolo" />
				<xsd:element ref="emailStudente" />
				<xsd:element ref="data" />
				<xsd:element ref="orario" />
				<xsd:element ref="descrizione" />
				<xsd:element ref="linkDocumento" />
				<xsd:element ref="visualizzazioni" />
				<xsd:element ref="tags" />
				<xsd:element ref="preferiti" />
			</xsd:sequence>
			<xsd:attribute ref="condivisione" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="riassunti">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="riassunto"  minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute ref="lastID" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pietro-nardelli/Stoudy/xml-schema/riassunti.xml
<?xml version="1.0" encoding="UTF-8"?>
<riassunti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="riassunti.xsd"><riassunto condivisione="pubblico"><ID>1</ID><titolo>Questo è un riassunto di prova</titolo><emailStudente>pietro.nardelliz@gmail.com</emailStudente><data>2017-10-14</data><orario>16:39:44</orario><descrizione>Questa è la descrizione del riassunto, consiste nel dire ciò che si vuole dire prima di presentare il PDF sottostante.</descrizione><linkDocumento>uploads/1507991984.pdf</linkDocumento><visualizzazioni>0</visualizzazioni><tags><nomeTag>prova</nomeTag><nomeTag>riassunto</nomeTag></tags><preferiti/></riassunto><riassunto condivisione="pubblico"><ID>2</ID><titolo>Secondo riassunto di prova</titolo><emailStudente>pietro.nardelliz@gmail.com</emailStudente><data>2017-10-14</data><orario>16:41:12</orario><descrizione/><linkDocumento>uploads/1507992072.pdf</linkDocumento><visualizzazioni>0</visualizzazioni><tags><nomeTag>boarding pass</nomeTag></tags><preferiti/></riassunto><riassunto condivisione="pubblico"><ID>3</ID><titolo>Un altro riassunto di prova</titolo><emailStudente>pietro.nardelliz@gmail.com</emailStudente><data>2017-10-14</data><orario>16:51:45</orario><descrizione/><linkDocumento>uploads/1507992705.pdf</linkDocumento><visualizzazioni>0</visualizzazioni><tags><nomeTag>asdfaf</nomeTag></tags><preferiti/></riassunto><riassunto condivisione="privato"><ID>4</ID><titolo>Un altro ancora riassunto di prova</titolo><emailStudente>pietro.nardelliz@gmail.com</emailStudente><data>2017-10-14</data><orario>17:27:07</orario><descrizione>ciaociao</descrizione><linkDocumento>uploads/1507994827.pdf</linkDocumento><visualizzazioni>0</visualizzazioni><tags><nomeTag>ciao</nomeTag><nomeTag>prova</nomeTag></tags><preferiti/></riassunto></riassunti>
