=== pietro-nardelli/Stoudy/xml-schema/tags.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple element -->
	<xsd:element name="nome" type="xsd:string" />
	<xsd:element name="descrizione" type="xsd:string" />
	<xsd:element name="riassuntoID" type="xsd:string" />

	<!-- definition of attributes -->
	<!-- definition of complex elements -->
	<xsd:element name="tag">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nome" />
				<xsd:element ref="descrizione" />
				<xsd:element ref="riassuntoID" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="tags">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tag"  minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pietro-nardelli/Stoudy/xml-schema/tags.xml
<?xml version="1.0"?>
<tags xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tags.xsd"><tag><nome>lorem</nome></tag><tag><nome>latino</nome></tag><tag><nome>prova</nome></tag><tag><nome>riassunto</nome></tag><tag><nome>ciao</nome></tag><tag><nome>inglese</nome></tag><tag><nome>ipsum</nome><riassuntoID>3</riassuntoID></tag><tag><nome>biologia</nome><riassuntoID>3</riassuntoID></tag><tag><nome>sadfsadf</nome><riassuntoID>3</riassuntoID><riassuntoID>1</riassuntoID><riassuntoID>3</riassuntoID><riassuntoID>4</riassuntoID><riassuntoID>5</riassuntoID></tag></tags>
